[package]
name = "tokenfoundry-core"
description = "Core library for TokenFoundry"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
ordered-float = { version = "5.3.0", features = ["serde"] }
petgraph = { version = "0.8.3", features = [
    "serde-1",
    "dot_parser",
    "graphmap",
] }
regex = "1.12.3"
schemars = { version = "1.0.2", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_spanned = "1.1.1"
thiserror = "2.0.17"
tracing = "0.1.44"

[dev-dependencies]
test-log = { version = "0.2.20", features = ["trace"] }
